version: '3.8'

services:

  # 1. Bootstrap Teleport config (auth+proxy+node)
  configure-teleport:
    image: public.ecr.aws/gravitational/teleport-distroless-debug:17.4.8
    container_name: teleport-configure
    entrypoint: ""
    command: >
      busybox sh -c
      "if [ ! -f /etc/teleport/teleport.yaml ];
       then teleport configure --roles=auth,proxy,node > /etc/teleport/teleport.yaml;
       fi"
    volumes:
      - ./config/teleport:/etc/teleport

  # 2. Teleport (auth, proxy & SSH node all in one)
  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless-debug:17.4.8
    container_name: teleport-all
    depends_on:
      - configure-teleport
    entrypoint: ""
    command: teleport start --roles=auth,proxy,node
    volumes:
      - ./config/teleport/teleport.yaml:/etc/teleport/teleport.yaml
      - teleport-data:/var/lib/teleport
    ports:
      - "3025:3025"   # auth service
      - "3080:3080"   # web UI
      - "3023:3023"   # proxy SSH
      - "3022:3022"   # node SSH
    networks:
      - teleport-net

  # 3. MariaDB backend
  mariadb:
    image: mariadb:10.11
    container_name: demo-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: StrongRootPass!
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: DemoPass123
    ports:
      - "3306:3306"
    networks:
      - teleport-net

volumes:
  teleport-data:

networks:
  teleport-net:
    driver: bridge
